# Generated by Django 2.2.3 on 2020-03-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('url_imagen', models.URLField(max_length=255)),
                ('dias_semana', models.CharField(max_length=32)),
            ],
        ),
    ]
